import type { Metadata } from "next";
import "@/app/styles/main.scss";
import MainLayout from "./layouts/MainLayout";

export const metadata: Metadata = {
  title: "MSM",
  description: "Generated by Adham Sherbiny",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
